/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.guiaps;

import java.awt.Dimension;
import java.awt.Toolkit; // library untuk mengatur agar jframe ditampilkan di tengah monitor
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;

/**
 *
 * @author manalu
 */
public class tiketpesawat extends javax.swing.JFrame {
    
    void on(){
    vabank.setEnabled(true); //jika bayar via transfer maka maka Combo Box aktif
    }
    void off(){
        vabank.setEnabled(false); // jika bayar  cash maka Combo Box vabank nonaktif
    }
    
    
    void aktif(){
        txtbayar.setEnabled(true);
        txtuangkembali.setEnabled(true); //jika bayar cash maka textfil bayar dan kembali aktif
    }
    void nonaktif(){
        txtbayar.setEnabled(false);
        txtuangkembali.setEnabled(false);  //jika bayar via transfer maka textfil bayar dan kembali nonaktif
 }
    
    int economy,premium_economy,bisnis;
    int sub_total,penumpang,total,bayar,kembali;
  /**
     * Creates new form Aplikasi_Latihan
     */
    public tiketpesawat() {
        initComponents();
        // untuk mengatur agar jframe ditampilkan di tengah monitor
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width /2 - this.getSize().width /2;
        int y = layar.height /2 - this.getSize().height /2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dari = new javax.swing.JComboBox<>();
        ke = new javax.swing.JComboBox<>();
        txttanggalberangkat = new javax.swing.JTextField();
        txtasal = new javax.swing.JTextField();
        txttujuan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        maskapai = new javax.swing.JComboBox<>();
        txtmaskapai = new javax.swing.JTextField();
        batal = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtpenumpang = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtuangkembali = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtbayar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        boxtittle = new javax.swing.JComboBox<>();
        btncetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtstruk = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        rbeconomy = new javax.swing.JRadioButton();
        rbpremium = new javax.swing.JRadioButton();
        rbbisnis = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        vabank = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        pesanmetodepembayaran = new javax.swing.JLabel();
        pesanmetodepembayaran1 = new javax.swing.JLabel();
        pesanmetodepembayaran2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        metodepembayaran = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pesanpajak = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        pesanboarding = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nokursi = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        nopenerbangan = new javax.swing.JLabel();
        informasi_penerbangan = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        pesanpembayaran = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Booking_Tiket_Pesawat");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("TIKET PESAWAT");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Dari");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("Ke");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("Tanggal Berangkat");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("Jumlah Penumpang");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("Kelas Penerbangan");

        dari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bandara All Jakarta", "HLP", "CGK" }));
        dari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dariActionPerformed(evt);
            }
        });

        ke.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ke.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bandara Tujuan", "BPN", "SUB", "DPS", "KNO" }));
        ke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keActionPerformed(evt);
            }
        });

        txttanggalberangkat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtasal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txttujuan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 153));
        jLabel10.setText("Nama Kota/Bandara Asal");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 153));
        jLabel11.setText("Nama Kota/Bandara Tujuan");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 153));
        jLabel12.setText("Maskapai Penerbangan");

        maskapai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        maskapai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maskapai Penerbangan", "citilink", "garuda", "batik", "lion", " " }));
        maskapai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maskapaiActionPerformed(evt);
            }
        });

        txtmaskapai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtmaskapai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaskapaiActionPerformed(evt);
            }
        });

        batal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        batal.setForeground(new java.awt.Color(0, 51, 153));
        batal.setText("BATAL");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Harga Total     Rp.");

        txtpenumpang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpenumpang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpenumpangActionPerformed(evt);
            }
        });
        txtpenumpang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpenumpangKeyReleased(evt);
            }
        });

        txttotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Sub Total         Rp. ");

        txtsubtotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtsubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubtotalActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Uang Kembali  Rp.");

        txtuangkembali.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtuangkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuangkembaliActionPerformed(evt);
            }
        });
        txtuangkembali.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtuangkembaliKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Bayar Cash       Rp.");

        txtbayar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbayarActionPerformed(evt);
            }
        });
        txtbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbayarKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Orang Dewasa");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 153));
        jLabel15.setText("Nama Penumpang");

        txtnama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        txtnama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnamaKeyPressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 153));
        jLabel16.setText("Tittle");

        boxtittle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boxtittle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tittle", "Tuan", "Nyonya" }));
        boxtittle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxtittleActionPerformed(evt);
            }
        });

        btncetak.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncetak.setForeground(new java.awt.Color(0, 51, 153));
        btncetak.setText("CETAK TIKET");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });

        txtstruk.setColumns(20);
        txtstruk.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtstruk.setRows(5);
        jScrollPane1.setViewportView(txtstruk);

        rbeconomy.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbeconomy.setText("Economy Class");
        rbeconomy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbeconomyActionPerformed(evt);
            }
        });

        rbpremium.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbpremium.setText("Premium Economy");
        rbpremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbpremiumActionPerformed(evt);
            }
        });

        rbbisnis.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbbisnis.setText("Business");
        rbbisnis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbbisnisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbbisnis, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbpremium)
                    .addComponent(rbeconomy))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rbeconomy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                .addComponent(rbpremium, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbbisnis)
                .addGap(15, 15, 15))
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 153));
        jLabel17.setText("BOARDING PASS");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Transfer via VA Bank");

        vabank.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vabank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih VA Bank", "VA Bank BCA", "VA Bank Mandiri", "VA Bank BRI", "VA Bank BNI", "VA Bank CIMB Niaga" }));
        vabank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vabankActionPerformed(evt);
            }
        });

        pesanmetodepembayaran.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        pesanmetodepembayaran1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        pesanmetodepembayaran2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pesanmetodepembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pesanmetodepembayaran1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pesanmetodepembayaran2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pesanmetodepembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(pesanmetodepembayaran1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(pesanmetodepembayaran2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Metode Pembayaran");

        metodepembayaran.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        metodepembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metode Pembayaran", "Cash", "Transfer Via VA Bank" }));
        metodepembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodepembayaranActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Harga Tiket");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Pembayaran");

        pesanpajak.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pesanpajak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pesanpajak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        pesanboarding.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        pesanboarding.setForeground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pesanboarding, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pesanboarding, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        nokursi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nokursi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nokursi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        nopenerbangan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nopenerbangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nopenerbangan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        informasi_penerbangan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        informasi_penerbangan.setText("Lihat informasi penerbangan");
        informasi_penerbangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informasi_penerbanganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pesanpembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pesanpembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, 11, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(322, 322, 322))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel5))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(batal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btncetak))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtbayar, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                                    .addComponent(txtuangkembali)))
                                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtasal, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dari, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtsubtotal)
                                            .addComponent(txttotal)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(maskapai, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(51, 51, 51)
                                                        .addComponent(jLabel19))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtmaskapai, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel18)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(metodepembayaran, 0, 172, Short.MAX_VALUE)
                                                    .addComponent(vabank, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtpenumpang, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel14))
                                            .addComponent(txttanggalberangkat, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ke, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(49, 49, 49)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txttujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel21)
                                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(195, 195, 195)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(boxtittle, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(139, 139, 139)
                                        .addComponent(jLabel1)))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(informasi_penerbangan)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(106, 106, 106)))))
                        .addGap(58, 58, 58)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(informasi_penerbangan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(62, 62, 62)
                                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(25, 25, 25)
                                            .addComponent(jLabel15))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(boxtittle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel20)
                                                .addComponent(dari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel10)
                                                .addComponent(txtasal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel13)
                                                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(txttujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txttanggalberangkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(maskapai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(metodepembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmaskapai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(vabank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addGap(50, 50, 50)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtpenumpang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtuangkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(batal)
                            .addComponent(btncetak))))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dariActionPerformed
        // TODO add your handling code here:
        if(dari.getSelectedItem().equals("Bandara All Jakarta")){
            buttonGroup1.clearSelection();
            txtsubtotal.setText("");
        }else if(dari.getSelectedItem().equals("HLP")){
            txtasal.setText("Halim Perdana Kusuma - Indonesia");
            txtasal.getText();
        }else if(dari.getSelectedItem().equals("CGK")){
            txtasal.setText("Cengkareng - Indonesia");
            txtasal.getText();
        }
    }//GEN-LAST:event_dariActionPerformed

    private void keActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keActionPerformed
        // TODO add your handling code here:
        if(dari.getSelectedItem().equals("Bandara Tujuan")){
            buttonGroup2.clearSelection();
        }else if(ke.getSelectedItem().equals("BPN")){
            txttujuan.setText("Balikpapan - Indonesia");
            txttujuan.getText();
            economy = 550000;
            premium_economy = 650000;
            bisnis = 850000;
        }else if(ke.getSelectedItem().equals("SUB")){
            txttujuan.setText("Surabaya - Indonesia");
            txttujuan.getText();
            economy = 450000;
            premium_economy = 600000;
            bisnis = 750000;
        }else if(ke.getSelectedItem().equals("DPS")){
            txttujuan.setText("Bali / Denpasar - Indonesia");
            txttujuan.getText();
            economy = 750000;
            premium_economy = 890000;
            bisnis = 1050000;
        }else if(ke.getSelectedItem().equals("KNO")){
            txttujuan.setText("Medan - Indonesia");
            txttujuan.getText();
            economy = 825000;
            premium_economy = 975000;
            bisnis = 1350000;
        }
    }//GEN-LAST:event_keActionPerformed

    private void maskapaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maskapaiActionPerformed
        // TODO add your handling code here:
        if(dari.getSelectedItem().equals("Maskapai Penerbangan")){
            buttonGroup3.clearSelection();
            txtmaskapai.setText("");
        }else if(maskapai.getSelectedItem().equals("citilink")){
            txtmaskapai.setText("CITILINK INDONESIA");
            txtmaskapai.getText();
        }else if(maskapai.getSelectedItem().equals("garuda")){
            txtmaskapai.setText("GARUDA INDONESIA");
            txtmaskapai.getText();
        }else if(maskapai.getSelectedItem().equals("batik")){
            txtmaskapai.setText("BATIK AIR");
            txtmaskapai.getText();           
        }else if(maskapai.getSelectedItem().equals("lion")){
            txtmaskapai.setText("LION AIR");
            txtmaskapai.getText();          
        }
    }//GEN-LAST:event_maskapaiActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(null,"Anda yakin membatalkan transaksi", "Keluar", JOptionPane.OK_OPTION);
        if(answer==JOptionPane.OK_OPTION){
            dispose(); 
        }
    }//GEN-LAST:event_batalActionPerformed

    private void rbbisnisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbisnisActionPerformed
        // TODO add your handling code here:
        if(rbbisnis.isSelected()){
            txtsubtotal.setText(String.valueOf(bisnis));
        }
    }//GEN-LAST:event_rbbisnisActionPerformed

    private void txtpenumpangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpenumpangKeyReleased
        // TODO add your handling code here:
        int a,b,c;
        a = Integer.valueOf(txtsubtotal.getText());
        b = Integer.valueOf(txtpenumpang.getText());
        c = a*b;
        txttotal.setText(""+c);
        pesanpajak.setText("Harga tiket sudah termasuk pajak");
        
    }//GEN-LAST:event_txtpenumpangKeyReleased

    private void rbeconomyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbeconomyActionPerformed
        // TODO add your handling code here:
        if(rbeconomy.isSelected()){
            txtsubtotal.setText(String.valueOf(economy));
        }
    }//GEN-LAST:event_rbeconomyActionPerformed

    private void rbpremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbpremiumActionPerformed
        // TODO add your handling code here:
        if(rbpremium.isSelected()){
            txtsubtotal.setText(String.valueOf(premium_economy));
        }
    }//GEN-LAST:event_rbpremiumActionPerformed

    private void txtbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbayarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtbayarActionPerformed

    private void txtpenumpangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpenumpangActionPerformed
        // TODO add your handling code here:
        penumpang = Integer.parseInt(txtpenumpang.getText());
        sub_total = Integer.parseInt(txtsubtotal.getText());
        total = bayar*sub_total;
        txttotal.setText(String.valueOf(total));
    }//GEN-LAST:event_txtpenumpangActionPerformed

    private void txtbayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbayarKeyReleased
        // TODO add your handling code here:
        int a,b,c;
        a = Integer.valueOf(txtbayar.getText());
        b = Integer.valueOf(txttotal.getText());
        c = a-b;
        txtuangkembali.setText(""+c);
    }//GEN-LAST:event_txtbayarKeyReleased

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txttotalActionPerformed

    private void txtsubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubtotalActionPerformed

    private void txtuangkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuangkembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuangkembaliActionPerformed

    private void txtuangkembaliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuangkembaliKeyReleased
        // TODO add your handling code here
        
    }//GEN-LAST:event_txtuangkembaliKeyReleased

    private void txtmaskapaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaskapaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaskapaiActionPerformed

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        // TODO add your handling code here
        if(maskapai.getSelectedItem().equals("citilink")){
            txtmaskapai.setText("CITILINK INDONESIA");
            pesanboarding.setText("CITILINK INDONESIA");
        }else if(maskapai.getSelectedItem().equals("garuda")){
            txtmaskapai.setText("GARUDA INDONESIA");
            pesanboarding.setText("GARUDA INDONESIA");
        }else if(maskapai.getSelectedItem().equals("batik")){
            txtmaskapai.setText("BATIK AIR");
            pesanboarding.setText("BATIK AIR");
        }else if(maskapai.getSelectedItem().equals("lion")){
            txtmaskapai.setText("LION AIR");
            pesanboarding.setText("LION AIR");
        }
      
        txtstruk.setText(
            "Nama Penumpang             : "+boxtittle.getSelectedItem()+"."+txtnama.getText()+"\n\n"+
            "Kota/Bandara Asal          : "+dari.getSelectedItem()+"\n\n"+
            "Nama Kota/Bandara Asal     : "+txtasal.getText()+"\n\n"+
            "Kota/Bandara Tujuan        : "+ke.getSelectedItem()+"\n\n"+
            "Nama Kota/Bandara Tujuan   : "+txttujuan.getText()+"\n\n"+
            "Tanggal Berangkat          : "+txttanggalberangkat.getText()+"\n\n"+
            "Maskapai Penerbangan       : "+txtmaskapai.getText()+"\n\n"+
            "Kelas Penerbangan          : "+jPanel1.getName()+"\n\n"+
            "Nomor kursi                : "+nokursi.getText()+"\n\n"+
            "Nomor Penerbangan          : "+nopenerbangan.getText()+"\n\n"+
            "Jumlah Penumpang           : "+txtpenumpang.getText()+"Orang dewasa"+"\n\n"+
            "Sub Total                  Rp. "+txtsubtotal.getText()+"\n\n"+
            "Harga Total                Rp. "+txttotal.getText()+"\n\n"+
            "Bayar                      Rp. "+txtbayar.getText()+"\n\n"+
            "Uang Kembali               Rp. "+txtuangkembali.getText()+"\n\n"+
            "Metode Pembayaran          : "+metodepembayaran.getSelectedItem()+"\n\n"+
            "Nama Bank                  : "+vabank.getSelectedItem()+"-->"+pesanmetodepembayaran.getText()
        );
    }//GEN-LAST:event_btncetakActionPerformed

    private void vabankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vabankActionPerformed
        // TODO add your handling code here:
        if(vabank.getSelectedItem().equals("Pilih VA Bank")){
            pesanmetodepembayaran.setText("Silahkan pilih salah satu va bank");
            buttonGroup8.clearSelection();
            pesanpembayaran.setText(" ");
        }else if(vabank.getSelectedItem().equals("VA Bank BCA")){
            pesanmetodepembayaran.setText("VA BCA        : 0156345674345678");
            pesanpembayaran.setText("*batas transfer 1 x 24 jam");
        }else if(vabank.getSelectedItem().equals("VA Bank Mandiri")){
            pesanmetodepembayaran.setText("VA MANDIRI    : 9876543200234681");
            pesanpembayaran.setText("*batas transfer 1 x 24 jam");
        }else if(vabank.getSelectedItem().equals("VA Bank BRI")){
            pesanmetodepembayaran.setText("VA BRI        : 6590002203327584");
            pesanpembayaran.setText("*batas transfer 1 x 24 jam");
        }else if(vabank.getSelectedItem().equals("VA Bank BNI")){
            pesanmetodepembayaran.setText("VA BNI        : 5753200983711668");
            pesanpembayaran.setText("*batas transfer 1 x 24 jam");
        }else if(vabank.getSelectedItem().equals("VA Bank CIMB Niaga")){
            pesanmetodepembayaran.setText("VA CIMB Niaga : 2546738976529800");
            pesanpembayaran.setText("*batas transfer 1 x 24 jam");
        }
    }//GEN-LAST:event_vabankActionPerformed

    private void metodepembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodepembayaranActionPerformed
        // TODO add your handling code here:
        if(metodepembayaran.getSelectedItem().equals("Metode Pembayaran")){
            buttonGroup9.clearSelection();
            pesanmetodepembayaran.setText("Silhkan pilih salah satu metode pembayaran");
        }else if(metodepembayaran.getSelectedItem().equals("Cash")){
            off();
            aktif();
            pesanmetodepembayaran.setText("Silahkan masukkan nominal bayar");
            bayar = Integer.parseInt(txtbayar.getText());
            kembali = Integer.parseInt(txttotal.getText());
            total = bayar-kembali;
            txtuangkembali.setText(String.valueOf(total));
        }else if(metodepembayaran.getSelectedItem().equals("Transfer Via VA Bank")){
            on();
            nonaktif();
            pesanmetodepembayaran.setText("Silahkan pilih salah satu Bank");
        }
    }//GEN-LAST:event_metodepembayaranActionPerformed

    private void informasi_penerbanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informasi_penerbanganActionPerformed
        // TODO add your handling code here:
        if(maskapai.getSelectedItem().equals("citilink")){
            nokursi.setText("Nomor Kursi --> 1A");
            nopenerbangan.setText("Nomor Penerbangan --> CTL150");
        }else if(maskapai.getSelectedItem().equals("garuda")){
            nokursi.setText("Nomor Kursi --> 2A");
            nopenerbangan.setText("Nomor Penerbangan --> GRD145");
        }else if(maskapai.getSelectedItem().equals("batik")){
            nokursi.setText("Nomor Kursi --> 3A");
            nopenerbangan.setText("Nomor Penerbangan --> BTK165");
        }else if(maskapai.getSelectedItem().equals("lion")){
            nokursi.setText("Nomor Kursi --> 4A");
            nopenerbangan.setText("Nomor Penerbangan -->Lion325");
        }else {
            nokursi.setText("silahkan input maskapai yang tersedia");
            nopenerbangan.setText("data tidak dapat ditampilkan");
        }
        
    }//GEN-LAST:event_informasi_penerbanganActionPerformed

    private void txtnamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamaKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaKeyPressed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void boxtittleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxtittleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxtittleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tiketpesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tiketpesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tiketpesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tiketpesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tiketpesawat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JComboBox<String> boxtittle;
    private javax.swing.JButton btncetak;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JComboBox<String> dari;
    private javax.swing.JToggleButton informasi_penerbangan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> ke;
    private javax.swing.JComboBox<String> maskapai;
    private javax.swing.JComboBox<String> metodepembayaran;
    private javax.swing.JLabel nokursi;
    private javax.swing.JLabel nopenerbangan;
    private javax.swing.JLabel pesanboarding;
    private javax.swing.JLabel pesanmetodepembayaran;
    private javax.swing.JLabel pesanmetodepembayaran1;
    private javax.swing.JLabel pesanmetodepembayaran2;
    private javax.swing.JLabel pesanpajak;
    private javax.swing.JLabel pesanpembayaran;
    private javax.swing.JRadioButton rbbisnis;
    private javax.swing.JRadioButton rbeconomy;
    private javax.swing.JRadioButton rbpremium;
    private javax.swing.JTextField txtasal;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtmaskapai;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtpenumpang;
    private javax.swing.JTextArea txtstruk;
    private javax.swing.JTextField txtsubtotal;
    private javax.swing.JTextField txttanggalberangkat;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttujuan;
    private javax.swing.JTextField txtuangkembali;
    private javax.swing.JComboBox<String> vabank;
    // End of variables declaration//GEN-END:variables
}

